### ISSUE TITLE
提个建议。

### ISSUE THREAD

**Issue by kaneawk** [breakwa11/shadowsocks-csharp#12]
在编辑服务器对话框，服务器区域，UDP over TCP 后面能否加个switch（显示原版SS二维码）。用于切换 SSR与原版SS的二维码。这样就方便多了。

**Comment by breakwa11** [comment]
新版中只要没有开混淆和用原版协议就是原版的二维码了

**Comment by kaneawk** [comment]
但是这样会很麻烦。假如节点很多，需要一个一个的去改origin，然后保存重新打开，才会是原版二维码。

**Comment by breakwa11** [comment]
修改之后点一下“链接”右边的文本框，二维码就立即变更为当前设置，并不需要保存
