### ISSUE TITLE
不能正常更新PAC

### ISSUE THREAD

**Issue by Amonhuz** [breakwa11/shadowsocks-csharp#15]
3.7.2开始4个更新PAC的功能都不能使用，提示 'Failed to update PAC file'，服务器配置没变，3.7.1之前正常，最新的3.7.3也还是不行。
本地代理可以正常使用。

日志只有一条
[2016-01-11 18:50:20] ShadowsocksR started

**Comment by breakwa11** [comment]
3.7.3.1已修好
