### ISSUE TITLE
3.6.9开始 上传速度很慢

### ISSUE THREAD

**Issue by aglent** [breakwa11/shadowsocks-csharp#16]
3台SS服务器 2个Shadowsocks版本，一个是clowwindy的version 2.4，一个是你们的。
反复测试结果，clowwindy 2.4的版本上传速度稳定，平均5MB/s。
你们的版本，3.6.9以上，包含3.6.9,3.7.0,3.7.3等，上传速度只有300多KB/s，把版本降到3.5.9或3.5.6，上传速度立即恢复正常。
较新的版本下载似乎也慢了一点点，但基本正常。
测试了很多遍，看到这个结果比较奇怪，麻烦作者确认下。
另：我用的是.net 2.0的exe文件。

**Comment by breakwa11** [comment]
由于上传带宽限制，无法复现你的问题，你用的是原协议吗？具体配置是什么？

**Comment by aglent** [comment]
客户端是默认配置的，TCP protocol是Original，Obfs是plain，加密是AES-256-cfb。

**Comment by breakwa11** [comment]
新版已解决
