### ISSUE TITLE
增加复数代理端口的功能

### ISSUE THREAD

**Issue by Explorare** [breakwa11/shadowsocks-csharp#19]
希望能支持同时开启多个代理端口，然后从服务器池中选择几条特定线路作为上行线路，意义就是能够更方便的访问某些对访问 IP 有地区限制的服务（比如 DMM 代理的游戏都限制只能使用日本 IP 访问）。SS 目前最大的问题是流量一大就容易被识别然后干扰，至少我的体验是这样的，切换一条线路就能暂时缓解丢包问题，但也撑不了多久又会受到干扰。所以希望能专门给游戏设置一个上行端口，使用日本的几条线路，其余使用另一个端口，走美国线路，至少能保证游戏连接能更稳定一些。目前我是运行了多个 SS 进程来实现此功能，但是很容易搞混配置，不如直接在一个进程中实现多端口的监听。

**Comment by breakwa11** [comment]
你没有开混淆或其它协议吗

**Comment by Explorare** [comment]
没有
