### ISSUE TITLE
你的源代码放在visualstudio2013里无法编译

### ISSUE THREAD

**Issue by MONOY** [breakwa11/shadowsocks-csharp#2]
提示缺少文件
C:\Users\JerryB\Source\Repos\shadowsocks-csharp\shadowsocks-csharp\shadowsocks-csharp4.0.csproj : error  : 未能加载项目文件。未能找到文件“C:\Users\JerryB\Source\Repos\shadowsocks-csharp\shadowsocks-csharp\shadowsocks-csharp4.0.csproj”。  C:\Users\JerryB\Source\Repos\shadowsocks-csharp\shadowsocks-csharp\shadowsocks-csharp4.0.csproj

**Comment by breakwa11** [comment]
这个工程文件漏了提交了，不过不影响，是一个重复工程，删掉就行了

**Comment by MONOY** [comment]
错误	1	无法创建“View\ServerLogForm.resx”的清单资源名称。未能找到文件“C:\Users\JerryB\Source\Repos\shadowsocks-csharp\shadowsocks-csharp\View\ServerLogForm.cs”。	shadowsocks-csharp

**Comment by MONOY** [comment]
错误	2	未能找到元数据文件“C:\Users\JerryB\Source\Repos\shadowsocks-csharp\shadowsocks-csharp\bin\x86\Debug\ShadowsocksR.exe”	C:\Users\JerryB\Source\Repos\shadowsocks-csharp\test\CSC	test

**Comment by MONOY** [comment]
这两个是什么原因？我没开发过C# vs2013也是第一次用，需要提前设置什么吗？

**Comment by breakwa11** [comment]
好吧，看来漏了不少东西，我补补去

**Comment by ARwMq9b6** [comment]
@breakwa11 网友希望您注意保护自己， <https://code.google.com/p/goagent/issues/detail?id=22378#c61> 。

**Comment by breakwa11** [comment]
已补漏，请测试

**Comment by MONOY** [comment]
已经测试，编译运行成功。3Q，望注意保护个人隐私。
