### ISSUE TITLE
为负载均衡增加伺服器组功能

### ISSUE THREAD

**Issue by Explorare** [breakwa11/shadowsocks-csharp#20]
当前的负载均衡默认是使用已添加的所有伺服器，对于添加了多条不同国家和地区的线路的用户来说，如果能够自定义负载均衡策略，给不同配置文件添加不同的伺服器组会方便很多，比如 DMM 代理的游戏都是日本 IP 限定的，而如果所有流量都走了日本线路会影响连接的可靠性，比如容易被识别干扰。具体来说，我希望能配置两个伺服器组，一个全部是日本线路用于游戏，另一个使用其他线路用于网页浏览，这里还需要多端口的功能，见 #19

**Comment by breakwa11** [comment]
已有，要多端口自己多开客户端
