### ISSUE TITLE
增加多层代理链路功能

### ISSUE THREAD

**Issue by Explorare** [breakwa11/shadowsocks-csharp#21]
当前只能找到设定双层代理的功能，希望能够进一步增加自定义多重代理链路功能，类似于 Proxifier 的 Proxy Chains 功能，并且能从多个 profiles 中方便的切换来更改访问路径。

**Comment by breakwa11** [comment]
多层代理与proxy chains含义不同

**Comment by Explorare** [comment]
那么是否可以将 SS 的流量再次封装到 SS 流量中呢？有时候日本线路不好了还得想办法从美国绕行。

**Comment by HuanMeng0** [comment]
SS 的流量再次封装到 SS 流量。你可以试试利用iptables做流量转发

**Comment by Explorare** [comment]
感谢帮助，流量转发得在伺服器端设置，我的想法是，如果我只拥有线路的接入权限而没有伺服器的管理权限，如何有效整合现有线路资源进行绕行或者多层代理。

**Comment by HuanMeng0** [comment]
在路由层面进行转发

**Comment by Explorare** [comment]
kwsk

**Comment by breakwa11** [comment]
自己看帮助文档，都写了那么久的多重代理配置示例
