### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by aprikyblue** [breakwa11/shadowsocks-csharp#23]
Ver: 3.7.4.1

all software in my computer can't connect to the ssr local port ( using 1080)

I have checked all configurations, updated shadowsocksR, deleted the directory *temp*  and restarted, but useless

The logs were filled with ..
> [2016-02-03 18:55:12] System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.EntryPointNotFoundException: 无法在 DLL“libsscrypto”中找到名为“md5_init”的入口点。
   在 Shadowsocks.Encryption.MbedTLS.md5_init(IntPtr ctx)
   在 Shadowsocks.Encryption.MbedTLS.MD5(Byte[] input)
   在 Shadowsocks.Encryption.IVEncryptor.bytesToKey(Byte[] password, Byte[] key)
   在 Shadowsocks.Encryption.IVEncryptor.InitKey(String method, String password)
   在 Shadowsocks.Encryption.PolarSSLEncryptor..ctor(String method, String password)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle._InvokeConstructor(Object[] args, SignatureStruct& signature, IntPtr declaringType)
   在 System.RuntimeMethodHandle.InvokeConstructor(Object[] args, SignatureStruct signature, RuntimeTypeHandle declaringType)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Shadowsocks.Encryption.EncryptorFactory.GetEncryptor(String method, String password)
   在 Shadowsocks.Controller.Handler.Connect()
   在 Shadowsocks.Controller.Handler.StartConnect(IAsyncResult ar)
[2016-02-03 18:55:12] Void LogUsefulException(System.Exception)
Void StartConnect(System.IAsyncResult)
Void Complete(IntPtr)
Boolean CaptureOrComplete(System.Threading.ExecutionContext ByRef, Boolean)
Boolean FinishPostingAsyncOp(System.Net.CallbackClosure ByRef)
System.IAsyncResult BeginSend(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef, System.AsyncCallback, System.Object)
System.IAsyncResult BeginSend(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.AsyncCallback, System.Object)
Void RspSocks5TCPHeader()
Void HandshakeReceive2Callback(System.IAsyncResult)
Void Complete(IntPtr)
Void CompleteCallback(System.Object)
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Void Complete(IntPtr)
Void ProtectedInvokeCallback(System.Object, IntPtr)
Void CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
Void PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

BTW, The original version *shadowsocks/shadowsocks-windows* is working well.

**Comment by aprikyblue** [comment]
The same problem occurred also in the original version 3.0
shadowsocks/shadowsocks-windows@5d14999

**Comment by breakwa11** [comment]
win10?

**Comment by aprikyblue** [comment]
win10 pro x64

**Comment by breakwa11** [comment]
看半天没发现哪里是修正问题的代码，你自己编译的正常吗？

**Comment by aprikyblue** [comment]
a bit strange, but it works well now.

maybe my system problem
