### ISSUE TITLE
GFWList used in this project seems to be down?

### ISSUE THREAD

**Issue by ovizii** [breakwa11/shadowsocks-csharp#26]
Any alternative to https://github.com/clowwindy/gfwlist2pac available?

**Comment by xbb123** [comment]
Try Mono_PAC, it works well for me.
Good luck!

**Comment by ovizii** [comment]
And how does one do that? 
shadowsocks client has a button: "Update Local Pac from GFWList" that is all I have

**Comment by xbb123** [comment]
If you were to use PAC mode and by default, SSR will only proxy traffics that's been blocked in China. 
If you were to use PAC mode and want to customize PAC, you may use mono_pac to generate one; By default, mono_pac WILL proxy all websites that's not hosted in mainland China.

**Comment by xbb123** [comment]
And to reply to your title, no. GFWList is still an active project.
Link: https://github.com/gfwlist/gfwlist

**Comment by ovizii** [comment]
The link I gave above, which gives a 404 I is from within shadowsocks. 

If I go edit the local PAC file, it contains this on top: 
// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

var proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;";`

which led me to the assumption that the project is dead.

Thanks for the explanations and the correct link.

**Comment by breakwa11** [comment]
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
