### ISSUE TITLE
增加mac客户端支持

### ISSUE THREAD

**Issue by foxni** [breakwa11/shadowsocks-csharp#27]
OS X系统下一直用的shadowsocksX，可惜后来一直不更新了，windows下使用混淆协议后发现速度快了很多，不知道能否为OS X系统提供客户端支持，谢谢！

**Comment by chenyiping1995** [comment]
目前已经有用于GoAgentX的ShadowsocksR插件了，可以去G+看看。

**Comment by foxni** [comment]
试用了了一下，非常不错。
