### ISSUE TITLE
内置的socks5代理似乎有些问题

### ISSUE THREAD

**Issue by loveyanbei** [breakwa11/shadowsocks-csharp#30]
今天用androidstudio去连接默认的1080一直是read time out，但是使用系统代理的网页没问题。
建议privoxy的端口不要随机了，就指定一个固定的端口来监听，这样可以直接使用privoxy的http代理

**Comment by breakwa11** [comment]
那么请还是用1080端口并改为http代理协议，再再再说一次不要直接使用privoxy的端口
