### ISSUE TITLE
ShadowsocksR C# 版本3.7.4版本突然连接不能

### ISSUE THREAD

**Issue by BreezeSak** [breakwa11/shadowsocks-csharp#33]
[2016-05-17 12:07:44] ShadowsocksR started
[2016-05-17 12:07:54] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 Shadowsocks.Model.ServerSelectStrategy.Select(List`1 configs, Int32 curIndex, Int32 algorithm, Boolean forceChange)
   在 Shadowsocks.Model.Configuration.GetCurrentServer(Boolean usingRandom, Boolean forceRandom)
   在 Shadowsocks.Controller.Local.Handle(Byte[] firstPacket, Int32 length, Socket socket)
   在 Shadowsocks.Controller.Listener.ReceiveCallback(IAsyncResult ar)

log中反复写入同样的内容，半天就写入了近1G....求解。

**Comment by BreezeSak** [comment]
从bittorrent上更新后log内容变成了
[2016-05-17 14:22:16] ShadowsocksR started
[2016-05-17 14:22:17] [Warn]Proxy server [(127.0.0.1)] connection refused

请问这是什么原因造成的？

**Comment by breakwa11** [comment]
因为你所有节点都禁用了

**Comment by BreezeSak** [comment]
多谢指教，在把配置文件删除重新导入服务器后恢复正常了
请问是因为开启了“自动禁用出错服务器”的原因吗？一般该如何取消对服务器的禁用？

**Comment by breakwa11** [comment]
开启了“自动禁用出错服务器”的时候，如果你突然断网了，就会导致自动把所有节点禁用了。要开启就打开服务器连接统计窗口，对指定节点开关

**Comment by BreezeSak** [comment]
原来这样...
感谢您在百忙之中抽时间解答，再次感谢。
