### ISSUE TITLE
http 混淆在移动4G网络环境下出错的问题

### ISSUE THREAD

**Issue by boyyao** [breakwa11/shadowsocks-csharp#36]
二次元妹子好。由于希望在手机中使用ssr的http混淆。但是发现移动会对发送的http header做修改。导致修改后client_encode生成的内容被剔除。看截取的包貌似是根据连续两个\n之后的内容会被剔除（尝试在参数中用\n\n测试后发现\n\n之后的内容没了）比如：
参数用www.baidu.com#User-Agent: 123\nAccept: text/html\n\nConnection: keep-alive
到服务器后就变成
GET /xxx HTTP/1.1
Host: www.baidu.com
User-Agent: abc
Accept: text/html
x-up-bear-type: TD-LTE
x-forwarded-for: 10.15.62.50
x-up-calling-line-id: 8613906609684
x-apn: cmnet
x-source-id: 10.0.78.7

注：Connection: keep-alive 没了。之后的加密字符串也没了。

例2 参数用（中间没有连续的\n\n）
www.baidu.com#User-Agent: 123\nAccept: text/html\nConnection: keep-alive
则到服务器之后的包内容为：
GET /xxx HTTP/1.1
Host: www.baidu.com
User-Agent: abc
Accept: text/html
Connection: keep-alive   <---这个就会出现
x-up-bear-type: TD-LTE
x-forwarded-for: 10.15.62.50
x-up-calling-line-id: 8613906609684
x-apn: cmnet
x-source-id: 10.0.78.7

所以初步判断移动默认会以\n\n作为header的结尾。并且结尾处添加自己的header

我的想法是能否在url中放置加密串？或者自定义的字段中放置加密串。并且缩短加密串的长度。以免构建出太大的header。

返回包中也做类似处理。用一个自定义的字段比如返回
HTTP/1.1 200 OK
Server: server
Code:加密串。。。
Content-Type: text/html
Content-Length: 2544
Connection: Keep-Alive

**Comment by breakwa11** [comment]
这样会导致特征可能会太明显，貌似移动这种做法是强行劫持http，因为原本的实现并不完整，一个严格点的代理也会把后面的过滤掉，也许之后会做一个完整的http实现以绕过限制，或者先用着tls1.2试试呢？

**Comment by boyyao** [comment]
想了一下。也许可以考虑以cookie的的方式来提交加密串用set cookie来返回 。cookie相对来说比较随意。并且加密串的强度实际上也并不用太复杂。只是用于区别是否是ssr发起的连接即可。或者在配置server和客户端的时候事先定义好一个简单的密匙也未尝不可。由于学校网络的限制。我只能以http混淆的方式才能出去~。如果针对学校和4G分别建一个server感觉有点繁琐~~ 希望二次元的宝宝能帮我解决一下。/磕头/磕头/磕头 O(∩_∩)O

**Comment by breakwa11** [comment]
我弄一个POST版本的http实现吧

**Comment by boyyao** [comment]
你太好了~~我要向你表白~~(づ｡◕‿‿◕｡)づ。能排队么？。
PS：除了Post 我在想connect方法是否也可以用于http混淆呢？而且get和post方法感觉一般都大多是单向传输数据的。比如一般GET除了首包和一些应答包之外都是返回数据的。而post则相反。唯有connect是相对来说“双工”的。并且connect一般用于https协议。内容本生就加密。如果伪装成 
connect www.baidu.com:443 http/1.1
host:www.baidu.com
类似于这样的包 我觉得gfw就很难甄别了吧？

**Comment by breakwa11** [comment]
@boyyao 这个貌似不太好，connect方法都用来做代理了，这行为太明显吧

**Comment by boyyao** [comment]
我没读过gfw的相关论文
但是我的想法是：
1，GFW不会针对HTTPS做中间人攻击，至少常规站点不会，也就是说不会截获HTTPS的访问内容。只会根据收个握手包的内容来判断是否drop链接。 （这个假设基本是成立的。因为有些被墙，主要是指得DNS污染的site，只要在hosts文件中指定一个正确的IP，然后用HTTPS访问就可以正常浏览，http访问就立即被dorp，也就是说有可能针对https甚至都不甄别数据包的host。应该更加不会甄别connect的内容了）

2，有可能针对全局甄别包的指纹。这个依靠伪装是没办法了。只能通过改变协议来避免。因为每个数据帧中都有可能包含被识别的指纹。这个无法通过收个包的混淆来欺骗gfw

3.伪装成http（get/post/connect）的好处。
首先当然是欺骗qos达到高优先级的目的了，已达到最大的网络利用率。虽然伪装本身耗费了一点网络资源或者cpu资源。但是得到的好处是不言而喻的。你的数据的优先级必定是提高了。。
以我的想法。一般的管理员至少不会吧http访问的qos级别定的太低吧？也许可能一些语音等数据会有更高的级别。但是通用性一定没http好。


伪装成http的好处2
很多学校或者公司都对非http的访问有所限制。甚至对http的访问都有部分限制。。
如果这样的话。ssr除了可以扶墙外。还能突破学校或者公司的某些限制了

我的想法还用http协议伪装（增加qos等级为主要目的）+减少协议的指纹 


当然http伪装的缺点也显而易见。。
太容易识别。但是如果伪装的好。伪装的正常，伪装的随机。则虽然容易被识别，但不容易被甄别。

甚至可以在server端直接模拟一个伪装目标site的反向代理，以防止gfw采取类似探针的方式来访问目标IP。看是否是正常的website

如果在理想状态。
1，本省协议没有被采集足够鉴别的指纹
2，没采取基于IP的白名单

只要这两个满足就可以永久的扶墙了。
个人拙见 么么哒··~~

**Comment by breakwa11** [comment]
> 甚至可以在server端直接模拟一个伪装目标site的反向代理，以防止gfw采取类似探针的方式来访问目标IP。看是否是正常的website

这个功能已经支持了，connect我考虑一下

**Comment by boyyao** [comment]
感谢回复。跪舔屏ing...
理想状态如果能实现GET、post、connect 整套的模拟伪装。那就堪称完美啊。当然加密串需要有自定义的key。以方式gfw自学习。 
因为一个正常的访问者不可能只有一个post、get、connect的方法的。必定是相互补充。

ps：目前的GET方法的path都是已定义的path中随机选取一个。。不知道能否改为以字典为基础的或者随机数为基础的随机路径+文件名+参数（?号后面的参数）这样更加没有规则可寻。或者直接点。让用户定义一个列表文件或者获取列表文件的接口之类的。，，

ps2：看你资料还未肉身翻墙。注意休息。么么哒哒~~~

**Comment by breakwa11** [comment]
可以测测新的http_post看能不能成功穿过，如果可以的话推上私聊
