### ISSUE TITLE
服务端设置了tls1.2_ticket_auth混肴，客户端设置plain也可以连线

### ISSUE THREAD

**Issue by didila** [breakwa11/shadowsocks-csharp#41]
以前因为服务端设置了_compatible所以没去注意
这次我决定把服务端的_compatible取消才发现
虽然服务端设置了"obfs": "tls1.2_ticket_auth“
可是客户端直接设置plain也是可以连线的
还有
我有设置"obfs_param"参数，客户端不需要设置也是可以正常连线
这是bug？还是兼容的问题？？

客户端ShadowsocksR-win-3.8.4.2e
服务端ShadowsocksR单人版

**Comment by breakwa11** [comment]
tls1.2的是BUG
服务端参数的意义和客户端的完全不一样，**千万不要**设置一样的参数，wiki上明明有说参数的意义的

**Comment by breakwa11** [comment]
已修复，更新服务端就行

**Comment by didila** [comment]
已测试确认没问题了

另外想请问
服务端的protocol_param参数可以设定连线数，而这个连线数指的是全部端口的连线数？还是单一端口的连线数？

**Comment by breakwa11** [comment]
不是连线数，是指连接这个端口的客户端的数量，这协议能准确知道有多少个客户端在使用，和IP无关，和连接数目无关

**Comment by didila** [comment]
謝謝，是我的問法錯誤，而你的回答正是我想知道的

**Comment by didila** [comment]
不好意思，再多问一次
protocol_param参数指的是端口的客户端数量，那如果是单人版多端口的话，protocol_param参数是面向各个单一端口的客户端数量？还是全部端口的客户端数量？

**Comment by breakwa11** [comment]
不管哪种模式，各端口相互独立

**Comment by didila** [comment]
同样的设置，用原版影梭居然可以连线，然后服务端log会出现一大堆错误，但是客户端却可以使用SSR翻墙

**Comment by breakwa11** [comment]
无法重现，请提供更具体的信息
