### ISSUE TITLE
PAC和全局代理切换困扰

### ISSUE THREAD

**Issue by gemnioo** [breakwa11/shadowsocks-csharp#43]
版本 Shadowsocks R-win-3.7.4.1. 两台电脑都遇到如下情况  已经禁用所有Chrome走代理的插件 

以我的理解 Internet 选项内 局域网设置

使用自动配置脚本 填入 Github在线的GFW名单  以为着走PAC  解析HTTP HTTPS的流量 

使用LAN 代理服务器 127.0.0.1  端口1080 是走全局代理  在TCP层面 用代理把系统的流量封装回了127.0.0.1 的LocalHost (感觉上去很像Surge TUN Interface ？）

但是遇到ShadowsocksR-win-3.7.4.1 版本下切换代理模式 并不会修改 局域网设置内的选择. 

而且第一次安装或／开关机后添加在线GFW地址后无法使用PAC (是否是第一次开启而gfw名单又挂在Github上 所以只能用全局)   使用全局后才能连上 但是切PAC模式后依旧走的是全局( 局域网设置内 勾选的是依旧是LAN模式 

并且Windows 7 旗舰版关闭Shadowsocks之后会无法上网 （因为LAN被设定了 127.0.0.1 端口1080)   而家庭版检查过 LAN 被修改了  却并不会出现这种情况 

请问是不是需要下载一个本地的PAC规则才能解决开机用PAC无法连接的情况？

Ps 代理用的是某东的  服务器在其他设备上确认过是正常的 

有点绕  希望你能看懂我的问题

**Comment by gemnioo** [comment]
Hi 我把挂在Github上的GFWlist 保存到本地就能完美支持PAC模式了  请关闭这个issue  谢谢.  已经完美支持

**Comment by breakwa11** [comment]
你应该更新版本

**Comment by breakwa11** [comment]
我正需要找人测试一下新版本是不是解决了这个问题

**Comment by gemnioo** [comment]
233 233 我一直都是全局切PAC才能实现PAC 想想也是GitHub被墙导致没有cache规则. 刚才灵光一现试了下就okay了 新版本能override 局域网设置了？ 还是解决了退出后改回默认的设置. 等下有空试下. 谢谢破娃酱. 一周年了.

**Comment by breakwa11** [comment]
我指的是局域网设置那

**Comment by breakwa11** [comment]
7 days ago

**Comment by gemnioo** [comment]
7 days ago 是什么鬼  麻烦可以关掉这个issue啦

**Comment by breakwa11** [comment]
说的就是7天你都没有给我任何反馈信息，为什么都解决了不告诉我一声

**Comment by gemnioo** [comment]
较真一下 

gemnioo commented 7 days ago
Hi 我把挂在Github上的GFWlist 保存到本地就能完美支持PAC模式了 请关闭这个issue 谢谢. 已经完美支持

and 我找不到3.7.4.1之后的测试版  把GFWlist加密的文档拷贝到本地txt就解决了 我也没去折腾 始终是PAC模式  也没有去切全局代理

**Comment by breakwa11** [comment]
我也较真一下，我问的是**“我指的是局域网设置那”**

因为你问**“新版本能override 局域网设置了？ 还是解决了退出后改回默认的设置”**

因为我前面说**“我正需要找人测试一下新版本是不是解决了这个问题”**

**Comment by gemnioo** [comment]
哦  我知道错了 别生气  我去下个3.2的最新版反省一下

**Comment by breakwa11** [comment]
不用反馈了，反正不再会更新了
