### ISSUE TITLE
最新3.8.9.0版有配置SS和SSR切换时自动勾选成SSR了

### ISSUE THREAD

**Issue by allismy** [breakwa11/shadowsocks-csharp#45]
描述：由于每次更新到新版的SSR时，我都是重新填写账号的。我有2个账号，一个SS和一个SSR,问题就产生了。
当我填完了一个SS完成了，此时是不需要勾选顶部的复选框的，当再添加一个填写SSR时是要勾选的（反之先填SSR后填SS也是对应勾和不勾）。填写完了就按确定完成了。这是通常就是这么干的，之前也没问题，可是当我打开GOOGLE时发现打不开了。更新PAC则提示“failed to update pac file”。
-----------------------------此处省略我浪费的时间，无奈-------------------------------------
问题：在于顶部复选框自动勾选的问题。有2种情况会自动勾选，一是当点击了一次勾选，之后就不管是不是SS,SSR都勾选就成了SSR,二是确定的时候自动勾选，因为SS没有混淆的，勾选时把SSR的混淆参数在SS也自动配置成SSR一样的，这样就和SS服务端不一致了。
希望尽快确认。

**Comment by breakwa11** [comment]
你重新描述一下你的操作过程？我重现不出来

**Comment by allismy** [comment]
@breakwa11  首先是假如账号为SSR类型的是没问题的。同时填写了SS的账号的话，
一是当点击左边框框里任意切换时，SS顶部的复选框就自动勾选了变成SSR了且把SSR的混淆配置也给SS配了一遍；
二是当点击确定按钮时，也会自动把SS勾选成SSR和前面一样(这个可以再次点开查看到)；
三还发现了一个，是点击SS下面的SSR连接时也会自动勾选。这3个都会导致与SS服务器不一致出现问题。
表达不好，不知道这次说清楚点了没。

**Comment by breakwa11** [comment]
你的第一点，无法重现，把你的设置界面截图来看看
第二点和第一点相同，
另外，你把你所用的exe文件计算一下SHA1发来

**Comment by XasaKura** [comment]
问题确实存在, 我也遇到了  首先ss ssr 都有  切换到ss 的界面, 点击下面的ssr链接 ,上面的 ssr会自动勾上,变成ssr的类型

**Comment by breakwa11** [comment]
@XasaKura 你的SS节点有把混淆之类的改回原版再点顶部的钩吗？其实顶部的钩不应该自己去打

**Comment by allismy** [comment]
我拼了一张图，是第一种情况的，后2种类似，程序sha1值也在拼图里了，这个框框上传图片真慢。
![default](https://cloud.githubusercontent.com/assets/10606051/18655273/02c191ec-7f1a-11e6-85c7-1614996b1503.png)

**Comment by breakwa11** [comment]
@allismy 你配置方式错了，并不是去掉最顶的钩它就变成SS节点，协议和混淆你没改

**Comment by XasaKura** [comment]
@breakwa11 当服务器是ss的h时候,底下的`SSR链接` 点击 会影响到上面的ShadowsocksR 复选框 , 就是这么设计的么?

**Comment by allismy** [comment]
@breakwa11 我觉得可以直接把顶部的复选框去掉，一律SSR,其实本来就是SSR,SS就直接默认的混淆方式，这样就容易使用了。

**Comment by breakwa11** [comment]
新版已解决
