### ISSUE TITLE
连接公司WiFi后无法使用

### ISSUE THREAD

**Issue by xx-li** [breakwa11/shadowsocks-csharp#50]
连接非公司WiFi可以正常翻墙，连接公司WiFi后就不行了。 不翻墙时公司的WiFi感觉和其他WiFi表现一致，可以访问所有没有被墙的网站。  请问这种是什么原因导致的？

**Comment by gloomy-ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/13086421/21467327/79b6f7ce-ca24-11e6-921d-e84e66f37262.png)
