### ISSUE TITLE
新版本？

### ISSUE THREAD

**Issue by Gigglelife** [breakwa11/shadowsocks-csharp#52]
~~Github 3.7.4.1 下载了运行提示有新版本 3.7.9，但是点链接跳转到 [ss for win](https://github.com/shadowsocks/shadowsocks-windows/releases?ShadowsocksR-win-dotnet4.0-3.7.9.7z)，并未有下载。Github不更新了？~~

**大致了解怎么回事了，原来还有这么多事！**

**Comment by szy0syz** [comment]
下载源码，剔除更新，然后编译。
^_^
