### ISSUE TITLE
v3.6.2.1 二维码连接问题

### ISSUE THREAD

**Issue by kaneawk** [breakwa11/shadowsocks-csharp#7]
使用SS Android手机端扫描由SSR提供的二维码后，

Android手机端 密码一栏变成：
ss://dGxzX3NpbXBsZTphZXMtMjU2LWNmYjpRb2U5ZmR2IUBqcDxxxxxx

加密方式一栏变成：
http_simple（obfs混淆插件一栏）

无语。w(ﾟДﾟ)w希望能解决一下。谢谢。

**Comment by breakwa11** [comment]
如果是带混淆的节点，手机端或其它客户端现在是没法扫的

**Comment by kaneawk** [comment]
能不能解决一下？

**Comment by aprikyblue** [comment]
带混淆的你扫了也没法用啊。。。

**Comment by missdeer** [comment]
你让服务商不要开混淆
